### PR TITLE
Use submodule for the ramdisk and improve tutorial

### PR DESCRIPTION
**Pull request by Uckermark**

### CODE REVIEW

**Review by dualra1n — APPROVED** [review]

**Comment by dualra1n** [comment]
> _ No description provided. _

very good and tysm

**Comment by dualra1n** [comment]
> _ No description provided. _

if I put ramdisk submodule, does that will clone it automatically

**Comment by Uckermark** [comment]
> if I put ramdisk submodule, does that will clone it automatically

If you clone with --recursive yes. Thats why i added it in the tutorial

**Review by dualra1n — APPROVED** [review]
very well , thank you :)

**Review by dualra1n — APPROVED** [review]
this is good, ty

**Pull request merged**
