### PR TITLE
I improved README.md a little

### PR DESCRIPTION
**Pull request by hostedbyjustus**
It's a bit better to read and understand and I also corrected some minor things I found

### CODE REVIEW

**Comment by hostedbyjustus** [comment]
Unfortunately I left in "(my fork)". Otherwise it should be flawless.

**Comment by edwin170** [comment]
> Unfortunately I left in "(my fork)". Otherwise it should be flawless.

lol true

**Comment by edwin170** [comment]
> Unfortunately I left in "(my fork)". Otherwise it should be flawless.

can't be (my fork) be removed ?

**Comment by edwin170** [comment]
thank you for this pl

**Pull request merged**
